# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jqgrid-rails3"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Heukmes"]
  s.date = "2012-04-02"
  s.description = "jQuery grid plugin for rails 3 packed as gem."
  s.email = "KharkivReM@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "lib/crud.rb",
    "lib/filter.rb",
    "lib/generators/jqgrid/USAGE",
    "lib/generators/jqgrid/jqgrid_generator.rb",
    "lib/generators/jqgrid/templates/controller.rb",
    "lib/generators/jqgrid/templates/index.html.erb",
    "lib/tasks/2dc_jqgrid_tasks.rake",
    "lib/view.rb",
    "public/javascripts/i18n/grid.locale-ar.js",
    "public/javascripts/i18n/grid.locale-bg.js",
    "public/javascripts/i18n/grid.locale-bg1251.js",
    "public/javascripts/i18n/grid.locale-cat.js",
    "public/javascripts/i18n/grid.locale-cn.js",
    "public/javascripts/i18n/grid.locale-cs.js",
    "public/javascripts/i18n/grid.locale-da.js",
    "public/javascripts/i18n/grid.locale-de.js",
    "public/javascripts/i18n/grid.locale-el.js",
    "public/javascripts/i18n/grid.locale-en.js",
    "public/javascripts/i18n/grid.locale-es.js",
    "public/javascripts/i18n/grid.locale-fa.js",
    "public/javascripts/i18n/grid.locale-fi.js",
    "public/javascripts/i18n/grid.locale-fr.js",
    "public/javascripts/i18n/grid.locale-gl.js",
    "public/javascripts/i18n/grid.locale-he.js",
    "public/javascripts/i18n/grid.locale-hu.js",
    "public/javascripts/i18n/grid.locale-is.js",
    "public/javascripts/i18n/grid.locale-it.js",
    "public/javascripts/i18n/grid.locale-ja.js",
    "public/javascripts/i18n/grid.locale-lt.js",
    "public/javascripts/i18n/grid.locale-mne.js",
    "public/javascripts/i18n/grid.locale-nl.js",
    "public/javascripts/i18n/grid.locale-no.js",
    "public/javascripts/i18n/grid.locale-pl.js",
    "public/javascripts/i18n/grid.locale-pt-br.js",
    "public/javascripts/i18n/grid.locale-pt.js",
    "public/javascripts/i18n/grid.locale-ro.js",
    "public/javascripts/i18n/grid.locale-ru.js",
    "public/javascripts/i18n/grid.locale-sk.js",
    "public/javascripts/i18n/grid.locale-sr.js",
    "public/javascripts/i18n/grid.locale-sv.js",
    "public/javascripts/i18n/grid.locale-th.js",
    "public/javascripts/i18n/grid.locale-tr.js",
    "public/javascripts/i18n/grid.locale-ua.js",
    "public/javascripts/jquery-1.7.min.js",
    "public/javascripts/jquery-ui-1.8.16.custom.min.js",
    "public/javascripts/jquery.jqGrid.min.js",
    "public/javascripts/jquery.jqGrid.src.js",
    "public/javascripts/ui.multiselect.js",
    "public/stylesheets/themes/default/images/ui-bg_diagonals-thick_90_eeeeee_40x40.png",
    "public/stylesheets/themes/default/images/ui-bg_flat_15_cd0a0a_40x100.png",
    "public/stylesheets/themes/default/images/ui-bg_glass_100_e4f1fb_1x400.png",
    "public/stylesheets/themes/default/images/ui-bg_glass_50_3baae3_1x400.png",
    "public/stylesheets/themes/default/images/ui-bg_glass_80_d7ebf9_1x400.png",
    "public/stylesheets/themes/default/images/ui-bg_highlight-hard_100_f2f5f7_1x100.png",
    "public/stylesheets/themes/default/images/ui-bg_highlight-hard_70_000000_1x100.png",
    "public/stylesheets/themes/default/images/ui-bg_highlight-soft_100_deedf7_1x100.png",
    "public/stylesheets/themes/default/images/ui-bg_highlight-soft_25_ffef8f_1x100.png",
    "public/stylesheets/themes/default/images/ui-icons_2694e8_256x240.png",
    "public/stylesheets/themes/default/images/ui-icons_2e83ff_256x240.png",
    "public/stylesheets/themes/default/images/ui-icons_3d80b3_256x240.png",
    "public/stylesheets/themes/default/images/ui-icons_72a7cf_256x240.png",
    "public/stylesheets/themes/default/images/ui-icons_ffffff_256x240.png",
    "public/stylesheets/themes/default/jquery-ui-1.8.custom.css",
    "public/stylesheets/ui.jqgrid.css",
    "public/stylesheets/ui.multiselect.css",
    "spec/2dcjqgrid_spec.rb",
    "test/filter_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://www.2dconcept.com/jquery-grid-rails-plugin"
  s.require_paths = ["lib tasks"]
  s.rubygems_version = "1.8.10"
  s.summary = "jQuery grid plugin for rails 3 packed as gem."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

